In [177]:
# https://www.youtube.com/watch?v=7eW8jzeKJuc&list=PLSLbhaYkTROErLvj0NOG9c1StJLwz1YLR&index=5

In [178]:
import datetime
import pandas as pd
pd.set_option('expand_frame_repr', False)

df = pd.read_csv('BTC-USD-1d.csv')

In [179]:
df['Date'] = pd.to_datetime(df['Date'])
df.dtypes

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [180]:
df[df['Date'] == '2013-04-02']
df.sample(5) # random 5 records

           Date         Open         High          Low        Close    Adj Close     Volume
363  2011-07-14    13.990000    14.090000    13.500000    13.810000    13.810000     344982
2569 2017-07-28  2806.750000  2812.129883  2699.419922  2733.500000  2733.500000  230818894
349  2011-06-30    16.100000    16.740000    15.260000    15.400000    15.400000     529197
1935 2015-11-03   359.279999   416.779999   354.579987   396.489990   396.489990  163481625
1439 2014-06-24   588.770020   589.559998   566.880005   568.450012   568.450012    1797681

In [181]:
df = df[['Date', 'Close']]

In [182]:
# define start and end date
startdate = '2013-12-04'
enddate = '2019-12-31'
df = df[(df['Date'] >= startdate) & (df['Date'] <= enddate)]

In [183]:
# calculate in amount

df['everytime_in'] = 100 # every week put in 100
df['accumulate_in'] = df['everytime_in'].cumsum() # cumulative_sum

c_rate = 0.002 # 手续费

df['everytime_buy_bt'] = df['everytime_in'] / df['Close'] * (1 - c_rate)
df['acc_buy_bt'] = df['everytime_buy_bt'].cumsum()

In [184]:
df

           Date        Close  everytime_in  accumulate_in  everytime_buy_bt  acc_buy_bt
1236 2013-12-04  1237.550049           100            100          0.080643    0.080643
1237 2013-12-05  1106.349976           100            200          0.090207    0.170850
1238 2013-12-06   845.020020           100            300          0.118104    0.288953
1239 2013-12-07   697.020020           100            400          0.143181    0.432134
1240 2013-12-08   803.960022           100            500          0.124136    0.556270
1241 2013-12-09   918.950012           100            600          0.108602    0.664872
1242 2013-12-10  1033.719971           100            700          0.096545    0.761417
1243 2013-12-11   919.929993           100            800          0.108487    0.869903
1244 2013-12-12   899.979980           100            900          0.110891    0.980795
1245 2013-12-13   936.770020           100           1000          0.106536    1.087331
1246 2013-12-14   908.940002           100           1100          0.109798    1.197129
1247 2013-12-15   919.880005           100           1200          0.108492    1.305621
1248 2013-12-16   759.919983           100           1300          0.131330    1.436951
1249 2013-12-17   714.969971           100           1400          0.139586    1.576537
1250 2013-12-18   540.979980           100           1500          0.184480    1.761017
1251 2013-12-19   731.950012           100           1600          0.136348    1.897366
1252 2013-12-20   649.960022           100           1700          0.153548    2.050913
1253 2013-12-21   640.479980           100           1800          0.155821    2.206734
1254 2013-12-22   639.489990           100           1900          0.156062    2.362796
1255 2013-12-23   713.239990           100           2000          0.139925    2.502721
1256 2013-12-24   702.750000           100           2100          0.142014    2.644734
1257 2013-12-25   707.250000           100           2200          0.141110    2.785844
1258 2013-12-26   801.979980           100           2300          0.124442    2.910286
1259 2013-12-27   803.049988           100           2400          0.124276    3.034562
1260 2013-12-28   761.989990           100           2500          0.130973    3.165535
1261 2013-12-29   784.960022           100           2600          0.127140    3.292676
1262 2013-12-30   804.830017           100           2700          0.124001    3.416677
1263 2013-12-31   805.940002           100           2800          0.123831    3.540507
1264 2014-01-01   815.940002           100           2900          0.122313    3.662820
1265 2014-01-02   856.909973           100           3000          0.116465    3.779285
...         ...          ...           ...            ...               ...         ...
3224 2019-05-14  8183.830078           100         198900          0.012195  315.470763
3225 2019-05-15  7874.109863           100         199000          0.012674  315.483438
3226 2019-05-16  7371.959961           100         199100          0.013538  315.496975
3227 2019-05-17  7266.080078           100         199200          0.013735  315.510711
3228 2019-05-18  8193.139648           100         199300          0.012181  315.522891
3229 2019-05-19  7998.290039           100         199400          0.012478  315.535369
3230 2019-05-20  7947.930176           100         199500          0.012557  315.547926
3231 2019-05-21  7626.890137           100         199600          0.013085  315.561011
3232 2019-05-22  7876.500000           100         199700          0.012671  315.573682
3233 2019-05-23  7996.399902           100         199800          0.012481  315.586162
3234 2019-05-24  8059.129883           100         199900          0.012383  315.598546
3235 2019-05-25  8726.230469           100         200000          0.011437  315.609983
3236 2019-05-26  8785.169922           100         200100          0.011360  315.621343
3237 2019-05-27  8718.849609           100         200200          0.011446  315.632789
3238 2019-05-28  8664.559570           100         200300          0.011518  315.644307
3239 2019-05-29  8276.250000           100         200400          0.012059  315.656366
3240 2019-05-30  8550.669922           100         200500          0.011672  315.668038
3241 2019-05-31  8555.870117           100         200600          0.011665  315.679702
3242 2019-06-01  8737.910156           100         200700          0.011421  315.691124
3243 2019-06-02  8114.490234           100         200800          0.012299  315.703422
3244 2019-06-03  7677.470215           100         200900          0.012999  315.716422
3245 2019-06-04  7791.290039           100         201000          0.012809  315.729231
3246 2019-06-05  7807.359863           100         201100          0.012783  315.742014
3247 2019-06-06  8002.629883           100         201200          0.012471  315.754484
3248 2019-06-07  7933.779785           100         201300          0.012579  315.767064
3249 2019-06-08  7643.439941           100         201400          0.013057  315.780121
3250 2019-06-09  8021.000000           100         201500          0.012442  315.792563
3251 2019-06-10  7917.319824           100         201600          0.012605  315.805168
3252 2019-06-11  8174.140137           100         201700          0.012209  315.817377
3253 2019-06-12  8218.299805           100         201800          0.012144  315.829521

[2018 rows x 6 columns]

In [185]:
# calculate market price
df['average_cost'] = df['accumulate_in'] / df['acc_buy_bt']
df['acc_value'] = df['acc_buy_bt'] * df['Close']
df

           Date        Close  everytime_in  accumulate_in  everytime_buy_bt  acc_buy_bt  average_cost     acc_value
1236 2013-12-04  1237.550049           100            100          0.080643    0.080643   1240.030109  9.980000e+01
1237 2013-12-05  1106.349976           100            200          0.090207    0.170850   1170.619281  1.890196e+02
1238 2013-12-06   845.020020           100            300          0.118104    0.288953   1038.229511  2.441715e+02
1239 2013-12-07   697.020020           100            400          0.143181    0.432134    925.637913  3.012063e+02
1240 2013-12-08   803.960022           100            500          0.124136    0.556270    898.844179  4.472188e+02
1241 2013-12-09   918.950012           100            600          0.108602    0.664872    902.429136  6.109843e+02
1242 2013-12-10  1033.719971           100            700          0.096545    0.761417    919.338945  7.870916e+02
1243 2013-12-11   919.929993           100            800          0.108487    0.869903    919.642566  8.002500e+02
1244 2013-12-12   899.979980           100            900          0.110891    0.980795    917.623376  8.826955e+02
1245 2013-12-13   936.770020           100           1000          0.106536    1.087331    919.683294  1.018579e+03
1246 2013-12-14   908.940002           100           1100          0.109798    1.197129    918.865007  1.088118e+03
1247 2013-12-15   919.880005           100           1200          0.108492    1.305621    919.102534  1.201015e+03
1248 2013-12-16   759.919983           100           1300          0.131330    1.436951    904.693287  1.091968e+03
1249 2013-12-17   714.969971           100           1400          0.139586    1.576537    888.022085  1.127177e+03
1250 2013-12-18   540.979980           100           1500          0.184480    1.761017    851.780344  9.526752e+02
1251 2013-12-19   731.950012           100           1600          0.136348    1.897366    843.274529  1.388777e+03
1252 2013-12-20   649.960022           100           1700          0.153548    2.050913    828.898965  1.333012e+03
1253 2013-12-21   640.479980           100           1800          0.155821    2.206734    815.685063  1.413369e+03
1254 2013-12-22   639.489990           100           1900          0.156062    2.362796    804.132084  1.510984e+03
1255 2013-12-23   713.239990           100           2000          0.139925    2.502721    799.130303  1.785041e+03
1256 2013-12-24   702.750000           100           2100          0.142014    2.644734    794.030620  1.858587e+03
1257 2013-12-25   707.250000           100           2200          0.141110    2.785844    789.706757  1.970288e+03
1258 2013-12-26   801.979980           100           2300          0.124442    2.910286    790.300274  2.333991e+03
1259 2013-12-27   803.049988           100           2400          0.124276    3.034562    790.888328  2.436905e+03
1260 2013-12-28   761.989990           100           2500          0.130973    3.165535    789.755851  2.412106e+03
1261 2013-12-29   784.960022           100           2600          0.127140    3.292676    789.631410  2.584619e+03
1262 2013-12-30   804.830017           100           2700          0.124001    3.416677    790.241549  2.749844e+03
1263 2013-12-31   805.940002           100           2800          0.123831    3.540507    790.847097  2.853437e+03
1264 2014-01-01   815.940002           100           2900          0.122313    3.662820    791.739630  2.988642e+03
1265 2014-01-02   856.909973           100           3000          0.116465    3.779285    793.800883  3.238507e+03
...         ...          ...           ...            ...               ...         ...           ...           ...
3224 2019-05-14  8183.830078           100         198900          0.012195  315.470763    630.486318  2.581759e+06
3225 2019-05-15  7874.109863           100         199000          0.012674  315.483438    630.777962  2.484151e+06
3226 2019-05-16  7371.959961           100         199100          0.013538  315.496975    631.067856  2.325831e+06
3227 2019-05-17  7266.080078           100         199200          0.013735  315.510711    631.357331  2.292526e+06
3228 2019-05-18  8193.139648           100         199300          0.012181  315.522891    631.649891  2.585123e+06
3229 2019-05-19  7998.290039           100         199400          0.012478  315.535369    631.941834  2.523743e+06
3230 2019-05-20  7947.930176           100         199500          0.012557  315.547926    632.233596  2.507953e+06
3231 2019-05-21  7626.890137           100         199600          0.013085  315.561011    632.524276  2.406749e+06
3232 2019-05-22  7876.500000           100         199700          0.012671  315.573682    632.815762  2.485616e+06
3233 2019-05-23  7996.399902           100         199800          0.012481  315.586162    633.107607  2.523553e+06
3234 2019-05-24  8059.129883           100         199900          0.012383  315.598546    633.399623  2.543450e+06
3235 2019-05-25  8726.230469           100         200000          0.011437  315.609983    633.693517  2.754085e+06
3236 2019-05-26  8785.169922           100         200100          0.011360  315.621343    633.987544  2.772787e+06
3237 2019-05-27  8718.849609           100         200200          0.011446  315.632789    634.281377  2.751955e+06
3238 2019-05-28  8664.559570           100         200300          0.011518  315.644307    634.575043  2.734919e+06
3239 2019-05-29  8276.250000           100         200400          0.012059  315.656366    634.867602  2.612451e+06
3240 2019-05-30  8550.669922           100         200500          0.011672  315.668038    635.160916  2.699173e+06
3241 2019-05-31  8555.870117           100         200600          0.011665  315.679702    635.454224  2.700915e+06
3242 2019-06-01  8737.910156           100         200700          0.011421  315.691124    635.747999  2.758481e+06
3243 2019-06-02  8114.490234           100         200800          0.012299  315.703422    636.039985  2.561772e+06
3244 2019-06-03  7677.470215           100         200900          0.012999  315.716422    636.330537  2.423903e+06
3245 2019-06-04  7791.290039           100         201000          0.012809  315.729231    636.621448  2.459938e+06
3246 2019-06-05  7807.359863           100         201100          0.012783  315.742014    636.912388  2.465112e+06
3247 2019-06-06  8002.629883           100         201200          0.012471  315.754484    637.203935  2.526866e+06
3248 2019-06-07  7933.779785           100         201300          0.012579  315.767064    637.495240  2.505226e+06
3249 2019-06-08  7643.439941           100         201400          0.013057  315.780121    637.785557  2.413646e+06
3250 2019-06-09  8021.000000           100         201500          0.012442  315.792563    638.077091  2.532972e+06
3251 2019-06-10  7917.319824           100         201600          0.012605  315.805168    638.368274  2.500331e+06
3252 2019-06-11  8174.140137           100         201700          0.012209  315.817377    638.660234  2.581536e+06
3253 2019-06-12  8218.299805           100         201800          0.012144  315.829521    638.952304  2.595582e+06

[2018 rows x 8 columns]