In [1]:
# https://www.youtube.com/watch?v=7eW8jzeKJuc&list=PLSLbhaYkTROErLvj0NOG9c1StJLwz1YLR&index=5

In [17]:
import datetime
import pandas as pd
pd.set_option('expand_frame_repr', False)

df = pd.read_csv('BTC-USD-1d.csv')

In [27]:
df['Date'] = pd.to_datetime(df['Date'])
df.dtypes
# print(df)


# daily to weekly data
logic = {'Open'  : 'first',
         'High'  : 'max',
         'Low'   : 'min',
         'Close' : 'last',
         'Volume': 'sum'}

offset = pd.offsets.timedelta(days=-6)

f = df.copy()
f.set_index('Date', inplace=True)

f = f.resample('W', loffset=offset).apply(logic)
f

                   Open         High          Low        Close      Volume
Date
2010-07-12     0.049510     0.093070     0.049510     0.080800          54
2010-07-19     0.080800     0.081810     0.050000     0.056000         489
2010-07-26     0.056000     0.069900     0.053000     0.060000        1803
2010-08-02     0.060000     0.073500     0.057000     0.071000        2379
2010-08-09     0.071000     0.075410     0.060000     0.065500        2755
2010-08-16     0.065500     0.076900     0.061200     0.064910        3596
2010-08-23     0.064910     0.069000     0.032110     0.064970        4294
2010-08-30     0.064970     0.064900     0.059610     0.061600        2706
2010-09-06     0.061600     0.065000     0.060140     0.062190        1934
2010-09-13     0.062190     0.175000     0.057610     0.062100        3697
2010-09-20     0.062100     0.063300     0.061470     0.062200        3637
2010-09-27     0.062200     0.062710     0.060810     0.061300        5803
2010-10-04     0.061300     0.130100     0.010000     0.095000       39774
2010-10-11     0.095000     0.119000     0.065000     0.102400       18290
2010-10-18     0.102400     0.190000     0.090090     0.132000       18616
2010-10-25     0.132000     0.199000     0.133000     0.192500       36919
2010-11-01     0.192500     0.500000     0.125000     0.340000       69258
2010-11-08     0.340000     0.370000     0.140000     0.279000       80006
2010-11-15     0.279000     0.290000     0.211600     0.276700       34775
2010-11-22     0.276700     0.289000     0.269000     0.270000       26129
2010-11-29     0.270000     0.279000     0.190000     0.190000       28408
2010-12-06     0.190000     0.247700     0.170100     0.220000       13487
2010-12-13     0.220000     0.255000     0.210000     0.240100        8909
2010-12-20     0.240100     0.275000     0.240000     0.265000       13799
2010-12-27     0.265000     0.301000     0.251000     0.300000       14483
2011-01-03     0.300000     0.323000     0.289000     0.323000       16315
2011-01-10     0.323000     0.450000     0.317500     0.386800       34960
2011-01-17     0.386800     0.444300     0.305000     0.442400       28826
2011-01-24     0.442400     0.480000     0.381000     0.479900       31537
2011-01-31     0.479900     0.950000     0.470000     0.899700      121369
...                 ...          ...          ...          ...         ...
2018-11-19  5615.259766  5615.979980  3550.040039  4004.149902  5413300148
2018-11-26  4004.459961  4444.390137  3598.810059  4143.859863  3517782866
2018-12-03  4143.859863  4159.009766  3248.000000  3592.840088  3062015272
2018-12-10  3592.840088  3645.489990  3169.530029  3255.370117  1665868727
2018-12-17  3255.370117  4247.709961  3239.060059  4007.629883  3088553290
2018-12-24  4007.629883  4303.370117  3622.389893  3896.209961  2156214537
2018-12-31  3896.209961  4145.160156  3696.939941  4102.850098  1310375609
2019-01-07  4102.850098  4156.160156  3528.239990  3551.239990  1613044716
2019-01-14  3551.239990  3799.620117  3529.250000  3567.729980  1207059124
2019-01-21  3567.729980  3676.399902  3473.770020  3565.080078   885743500
2019-01-28  3565.080078  3567.560059  3369.189941  3449.620117   957824266
2019-02-04  3449.620117  3735.100098  3362.239990  3685.139893   934711821
2019-02-11  3685.139893  3706.169922  3567.389893  3670.919922   927388858
2019-02-18  3670.919922  4221.620117  3661.419922  3771.620117  1785588324
2019-02-25  3771.620117  3909.860107  3699.530029  3812.310059   897355573
2019-03-04  3812.310059  3975.250000  3705.139893  3929.840088   918058460
2019-03-11  3929.840088  4069.110107  3825.030029  3998.000000   859459995
2019-03-18  3998.000000  4082.290039  3953.530029  3994.110107   784111053
2019-03-25  3994.110107  4164.330078  3887.679932  4151.319824   964376703
2019-04-01  4151.319824  5347.879883  4147.700195  5294.089844  3160485095
2019-04-08  5294.089844  5460.939941  4927.620117  5037.270020  1613671737
2019-04-15  5037.270020  5444.759766  5029.160156  5394.669922  1248778787
2019-04-22  5394.669922  5633.000000  5031.689941  5237.959961  1863423519
2019-04-29  5237.959961  5901.359863  5224.640137  5748.169922  1555846445
2019-05-06  5748.169922  8127.750000  5748.169922  7806.359863  4432348229
2019-05-13  7806.359863  8352.250000  6668.669922  7998.290039  5120308809
2019-05-20  7998.290039  8931.530273  7478.740234  8785.169922  2752269634
2019-05-27  8785.169922  9065.889648  8027.209961  8114.490234  3045095506
2019-06-03  8114.490234  8127.629883  7463.939941  8021.000000  2705695902
2019-06-10  8021.000000  8326.200195  7724.580078  8218.299805   995035160

[466 rows x 5 columns]

In [4]:
df[df['Date'] == '2013-04-02']
df.sample(5) # random 5 records

           Date         Open         High          Low        Close    Adj Close    Volume
2005 2016-01-12   447.720001   448.410004   443.140015   445.040009   445.040009  19913400
760  2012-08-14    12.190000    13.250000    12.160000    13.250000    13.250000    725834
306  2011-05-18     6.880000     7.340000     6.610000     6.810000     6.810000    170134
2472 2017-04-22  1240.890015  1256.229980  1223.060059  1249.140015  1249.140015  54224355
766  2012-08-20    10.100000    10.300000     9.700000     9.920000     9.920000    722740

In [5]:
df = df[['Date', 'Close']]

In [6]:
# define start and end date
startdate = '2013-12-04'
enddate = '2019-12-31'
df = df[(df['Date'] >= startdate) & (df['Date'] <= enddate)]

In [7]:
# calculate in amount

df['everytime_in'] = 100 # every week put in 100
df['accumulate_in'] = df['everytime_in'].cumsum() # cumulative_sum

c_rate = 0.002 # 手续费

df['everytime_buy_bt'] = df['everytime_in'] / df['Close'] * (1 - c_rate)
df['acc_buy_bt'] = df['everytime_buy_bt'].cumsum()

In [8]:
df

           Date        Close  everytime_in  accumulate_in  everytime_buy_bt  acc_buy_bt
1236 2013-12-04  1237.550049           100            100          0.080643    0.080643
1237 2013-12-05  1106.349976           100            200          0.090207    0.170850
1238 2013-12-06   845.020020           100            300          0.118104    0.288953
1239 2013-12-07   697.020020           100            400          0.143181    0.432134
1240 2013-12-08   803.960022           100            500          0.124136    0.556270
1241 2013-12-09   918.950012           100            600          0.108602    0.664872
1242 2013-12-10  1033.719971           100            700          0.096545    0.761417
1243 2013-12-11   919.929993           100            800          0.108487    0.869903
1244 2013-12-12   899.979980           100            900          0.110891    0.980795
1245 2013-12-13   936.770020           100           1000          0.106536    1.087331
1246 2013-12-14   908.940002           100           1100          0.109798    1.197129
1247 2013-12-15   919.880005           100           1200          0.108492    1.305621
1248 2013-12-16   759.919983           100           1300          0.131330    1.436951
1249 2013-12-17   714.969971           100           1400          0.139586    1.576537
1250 2013-12-18   540.979980           100           1500          0.184480    1.761017
1251 2013-12-19   731.950012           100           1600          0.136348    1.897366
1252 2013-12-20   649.960022           100           1700          0.153548    2.050913
1253 2013-12-21   640.479980           100           1800          0.155821    2.206734
1254 2013-12-22   639.489990           100           1900          0.156062    2.362796
1255 2013-12-23   713.239990           100           2000          0.139925    2.502721
1256 2013-12-24   702.750000           100           2100          0.142014    2.644734
1257 2013-12-25   707.250000           100           2200          0.141110    2.785844
1258 2013-12-26   801.979980           100           2300          0.124442    2.910286
1259 2013-12-27   803.049988           100           2400          0.124276    3.034562
1260 2013-12-28   761.989990           100           2500          0.130973    3.165535
1261 2013-12-29   784.960022           100           2600          0.127140    3.292676
1262 2013-12-30   804.830017           100           2700          0.124001    3.416677
1263 2013-12-31   805.940002           100           2800          0.123831    3.540507
1264 2014-01-01   815.940002           100           2900          0.122313    3.662820
1265 2014-01-02   856.909973           100           3000          0.116465    3.779285
...         ...          ...           ...            ...               ...         ...
3224 2019-05-14  8183.830078           100         198900          0.012195  315.470763
3225 2019-05-15  7874.109863           100         199000          0.012674  315.483438
3226 2019-05-16  7371.959961           100         199100          0.013538  315.496975
3227 2019-05-17  7266.080078           100         199200          0.013735  315.510711
3228 2019-05-18  8193.139648           100         199300          0.012181  315.522891
3229 2019-05-19  7998.290039           100         199400          0.012478  315.535369
3230 2019-05-20  7947.930176           100         199500          0.012557  315.547926
3231 2019-05-21  7626.890137           100         199600          0.013085  315.561011
3232 2019-05-22  7876.500000           100         199700          0.012671  315.573682
3233 2019-05-23  7996.399902           100         199800          0.012481  315.586162
3234 2019-05-24  8059.129883           100         199900          0.012383  315.598546
3235 2019-05-25  8726.230469           100         200000          0.011437  315.609983
3236 2019-05-26  8785.169922           100         200100          0.011360  315.621343
3237 2019-05-27  8718.849609           100         200200          0.011446  315.632789
3238 2019-05-28  8664.559570           100         200300          0.011518  315.644307
3239 2019-05-29  8276.250000           100         200400          0.012059  315.656366
3240 2019-05-30  8550.669922           100         200500          0.011672  315.668038
3241 2019-05-31  8555.870117           100         200600          0.011665  315.679702
3242 2019-06-01  8737.910156           100         200700          0.011421  315.691124
3243 2019-06-02  8114.490234           100         200800          0.012299  315.703422
3244 2019-06-03  7677.470215           100         200900          0.012999  315.716422
3245 2019-06-04  7791.290039           100         201000          0.012809  315.729231
3246 2019-06-05  7807.359863           100         201100          0.012783  315.742014
3247 2019-06-06  8002.629883           100         201200          0.012471  315.754484
3248 2019-06-07  7933.779785           100         201300          0.012579  315.767064
3249 2019-06-08  7643.439941           100         201400          0.013057  315.780121
3250 2019-06-09  8021.000000           100         201500          0.012442  315.792563
3251 2019-06-10  7917.319824           100         201600          0.012605  315.805168
3252 2019-06-11  8174.140137           100         201700          0.012209  315.817377
3253 2019-06-12  8218.299805           100         201800          0.012144  315.829521

[2018 rows x 6 columns]

In [9]:
# calculate market price
df['average_cost'] = df['accumulate_in'] / df['acc_buy_bt']
df['acc_value'] = df['acc_buy_bt'] * df['Close']
df

           Date        Close  everytime_in  accumulate_in  everytime_buy_bt  acc_buy_bt  average_cost     acc_value
1236 2013-12-04  1237.550049           100            100          0.080643    0.080643   1240.030109  9.980000e+01
1237 2013-12-05  1106.349976           100            200          0.090207    0.170850   1170.619281  1.890196e+02
1238 2013-12-06   845.020020           100            300          0.118104    0.288953   1038.229511  2.441715e+02
1239 2013-12-07   697.020020           100            400          0.143181    0.432134    925.637913  3.012063e+02
1240 2013-12-08   803.960022           100            500          0.124136    0.556270    898.844179  4.472188e+02
1241 2013-12-09   918.950012           100            600          0.108602    0.664872    902.429136  6.109843e+02
1242 2013-12-10  1033.719971           100            700          0.096545    0.761417    919.338945  7.870916e+02
1243 2013-12-11   919.929993           100            800          0.108487    0.869903    919.642566  8.002500e+02
1244 2013-12-12   899.979980           100            900          0.110891    0.980795    917.623376  8.826955e+02
1245 2013-12-13   936.770020           100           1000          0.106536    1.087331    919.683294  1.018579e+03
1246 2013-12-14   908.940002           100           1100          0.109798    1.197129    918.865007  1.088118e+03
1247 2013-12-15   919.880005           100           1200          0.108492    1.305621    919.102534  1.201015e+03
1248 2013-12-16   759.919983           100           1300          0.131330    1.436951    904.693287  1.091968e+03
1249 2013-12-17   714.969971           100           1400          0.139586    1.576537    888.022085  1.127177e+03
1250 2013-12-18   540.979980           100           1500          0.184480    1.761017    851.780344  9.526752e+02
1251 2013-12-19   731.950012           100           1600          0.136348    1.897366    843.274529  1.388777e+03
1252 2013-12-20   649.960022           100           1700          0.153548    2.050913    828.898965  1.333012e+03
1253 2013-12-21   640.479980           100           1800          0.155821    2.206734    815.685063  1.413369e+03
1254 2013-12-22   639.489990           100           1900          0.156062    2.362796    804.132084  1.510984e+03
1255 2013-12-23   713.239990           100           2000          0.139925    2.502721    799.130303  1.785041e+03
1256 2013-12-24   702.750000           100           2100          0.142014    2.644734    794.030620  1.858587e+03
1257 2013-12-25   707.250000           100           2200          0.141110    2.785844    789.706757  1.970288e+03
1258 2013-12-26   801.979980           100           2300          0.124442    2.910286    790.300274  2.333991e+03
1259 2013-12-27   803.049988           100           2400          0.124276    3.034562    790.888328  2.436905e+03
1260 2013-12-28   761.989990           100           2500          0.130973    3.165535    789.755851  2.412106e+03
1261 2013-12-29   784.960022           100           2600          0.127140    3.292676    789.631410  2.584619e+03
1262 2013-12-30   804.830017           100           2700          0.124001    3.416677    790.241549  2.749844e+03
1263 2013-12-31   805.940002           100           2800          0.123831    3.540507    790.847097  2.853437e+03
1264 2014-01-01   815.940002           100           2900          0.122313    3.662820    791.739630  2.988642e+03
1265 2014-01-02   856.909973           100           3000          0.116465    3.779285    793.800883  3.238507e+03
...         ...          ...           ...            ...               ...         ...           ...           ...
3224 2019-05-14  8183.830078           100         198900          0.012195  315.470763    630.486318  2.581759e+06
3225 2019-05-15  7874.109863           100         199000          0.012674  315.483438    630.777962  2.484151e+06
3226 2019-05-16  7371.959961           100         199100          0.013538  315.496975    631.067856  2.325831e+06
3227 2019-05-17  7266.080078           100         199200          0.013735  315.510711    631.357331  2.292526e+06
3228 2019-05-18  8193.139648           100         199300          0.012181  315.522891    631.649891  2.585123e+06
3229 2019-05-19  7998.290039           100         199400          0.012478  315.535369    631.941834  2.523743e+06
3230 2019-05-20  7947.930176           100         199500          0.012557  315.547926    632.233596  2.507953e+06
3231 2019-05-21  7626.890137           100         199600          0.013085  315.561011    632.524276  2.406749e+06
3232 2019-05-22  7876.500000           100         199700          0.012671  315.573682    632.815762  2.485616e+06
3233 2019-05-23  7996.399902           100         199800          0.012481  315.586162    633.107607  2.523553e+06
3234 2019-05-24  8059.129883           100         199900          0.012383  315.598546    633.399623  2.543450e+06
3235 2019-05-25  8726.230469           100         200000          0.011437  315.609983    633.693517  2.754085e+06
3236 2019-05-26  8785.169922           100         200100          0.011360  315.621343    633.987544  2.772787e+06
3237 2019-05-27  8718.849609           100         200200          0.011446  315.632789    634.281377  2.751955e+06
3238 2019-05-28  8664.559570           100         200300          0.011518  315.644307    634.575043  2.734919e+06
3239 2019-05-29  8276.250000           100         200400          0.012059  315.656366    634.867602  2.612451e+06
3240 2019-05-30  8550.669922           100         200500          0.011672  315.668038    635.160916  2.699173e+06
3241 2019-05-31  8555.870117           100         200600          0.011665  315.679702    635.454224  2.700915e+06
3242 2019-06-01  8737.910156           100         200700          0.011421  315.691124    635.747999  2.758481e+06
3243 2019-06-02  8114.490234           100         200800          0.012299  315.703422    636.039985  2.561772e+06
3244 2019-06-03  7677.470215           100         200900          0.012999  315.716422    636.330537  2.423903e+06
3245 2019-06-04  7791.290039           100         201000          0.012809  315.729231    636.621448  2.459938e+06
3246 2019-06-05  7807.359863           100         201100          0.012783  315.742014    636.912388  2.465112e+06
3247 2019-06-06  8002.629883           100         201200          0.012471  315.754484    637.203935  2.526866e+06
3248 2019-06-07  7933.779785           100         201300          0.012579  315.767064    637.495240  2.505226e+06
3249 2019-06-08  7643.439941           100         201400          0.013057  315.780121    637.785557  2.413646e+06
3250 2019-06-09  8021.000000           100         201500          0.012442  315.792563    638.077091  2.532972e+06
3251 2019-06-10  7917.319824           100         201600          0.012605  315.805168    638.368274  2.500331e+06
3252 2019-06-11  8174.140137           100         201700          0.012209  315.817377    638.660234  2.581536e+06
3253 2019-06-12  8218.299805           100         201800          0.012144  315.829521    638.952304  2.595582e+06

[2018 rows x 8 columns]

In [10]:
df['price_diff'] = df.Close.diff()
df

           Date        Close  everytime_in  accumulate_in  everytime_buy_bt  acc_buy_bt  average_cost     acc_value  price_diff
1236 2013-12-04  1237.550049           100            100          0.080643    0.080643   1240.030109  9.980000e+01         NaN
1237 2013-12-05  1106.349976           100            200          0.090207    0.170850   1170.619281  1.890196e+02 -131.200073
1238 2013-12-06   845.020020           100            300          0.118104    0.288953   1038.229511  2.441715e+02 -261.329956
1239 2013-12-07   697.020020           100            400          0.143181    0.432134    925.637913  3.012063e+02 -148.000000
1240 2013-12-08   803.960022           100            500          0.124136    0.556270    898.844179  4.472188e+02  106.940002
1241 2013-12-09   918.950012           100            600          0.108602    0.664872    902.429136  6.109843e+02  114.989990
1242 2013-12-10  1033.719971           100            700          0.096545    0.761417    919.338945  7.870916e+02  114.769959
1243 2013-12-11   919.929993           100            800          0.108487    0.869903    919.642566  8.002500e+02 -113.789978
1244 2013-12-12   899.979980           100            900          0.110891    0.980795    917.623376  8.826955e+02  -19.950013
1245 2013-12-13   936.770020           100           1000          0.106536    1.087331    919.683294  1.018579e+03   36.790040
1246 2013-12-14   908.940002           100           1100          0.109798    1.197129    918.865007  1.088118e+03  -27.830018
1247 2013-12-15   919.880005           100           1200          0.108492    1.305621    919.102534  1.201015e+03   10.940003
1248 2013-12-16   759.919983           100           1300          0.131330    1.436951    904.693287  1.091968e+03 -159.960022
1249 2013-12-17   714.969971           100           1400          0.139586    1.576537    888.022085  1.127177e+03  -44.950012
1250 2013-12-18   540.979980           100           1500          0.184480    1.761017    851.780344  9.526752e+02 -173.989991
1251 2013-12-19   731.950012           100           1600          0.136348    1.897366    843.274529  1.388777e+03  190.970032
1252 2013-12-20   649.960022           100           1700          0.153548    2.050913    828.898965  1.333012e+03  -81.989990
1253 2013-12-21   640.479980           100           1800          0.155821    2.206734    815.685063  1.413369e+03   -9.480042
1254 2013-12-22   639.489990           100           1900          0.156062    2.362796    804.132084  1.510984e+03   -0.989990
1255 2013-12-23   713.239990           100           2000          0.139925    2.502721    799.130303  1.785041e+03   73.750000
1256 2013-12-24   702.750000           100           2100          0.142014    2.644734    794.030620  1.858587e+03  -10.489990
1257 2013-12-25   707.250000           100           2200          0.141110    2.785844    789.706757  1.970288e+03    4.500000
1258 2013-12-26   801.979980           100           2300          0.124442    2.910286    790.300274  2.333991e+03   94.729980
1259 2013-12-27   803.049988           100           2400          0.124276    3.034562    790.888328  2.436905e+03    1.070008
1260 2013-12-28   761.989990           100           2500          0.130973    3.165535    789.755851  2.412106e+03  -41.059998
1261 2013-12-29   784.960022           100           2600          0.127140    3.292676    789.631410  2.584619e+03   22.970032
1262 2013-12-30   804.830017           100           2700          0.124001    3.416677    790.241549  2.749844e+03   19.869995
1263 2013-12-31   805.940002           100           2800          0.123831    3.540507    790.847097  2.853437e+03    1.109985
1264 2014-01-01   815.940002           100           2900          0.122313    3.662820    791.739630  2.988642e+03   10.000000
1265 2014-01-02   856.909973           100           3000          0.116465    3.779285    793.800883  3.238507e+03   40.969971
...         ...          ...           ...            ...               ...         ...           ...           ...         ...
3224 2019-05-14  8183.830078           100         198900          0.012195  315.470763    630.486318  2.581759e+06  203.700195
3225 2019-05-15  7874.109863           100         199000          0.012674  315.483438    630.777962  2.484151e+06 -309.720215
3226 2019-05-16  7371.959961           100         199100          0.013538  315.496975    631.067856  2.325831e+06 -502.149902
3227 2019-05-17  7266.080078           100         199200          0.013735  315.510711    631.357331  2.292526e+06 -105.879883
3228 2019-05-18  8193.139648           100         199300          0.012181  315.522891    631.649891  2.585123e+06  927.059570
3229 2019-05-19  7998.290039           100         199400          0.012478  315.535369    631.941834  2.523743e+06 -194.849609
3230 2019-05-20  7947.930176           100         199500          0.012557  315.547926    632.233596  2.507953e+06  -50.359863
3231 2019-05-21  7626.890137           100         199600          0.013085  315.561011    632.524276  2.406749e+06 -321.040039
3232 2019-05-22  7876.500000           100         199700          0.012671  315.573682    632.815762  2.485616e+06  249.609863
3233 2019-05-23  7996.399902           100         199800          0.012481  315.586162    633.107607  2.523553e+06  119.899902
3234 2019-05-24  8059.129883           100         199900          0.012383  315.598546    633.399623  2.543450e+06   62.729981
3235 2019-05-25  8726.230469           100         200000          0.011437  315.609983    633.693517  2.754085e+06  667.100586
3236 2019-05-26  8785.169922           100         200100          0.011360  315.621343    633.987544  2.772787e+06   58.939453
3237 2019-05-27  8718.849609           100         200200          0.011446  315.632789    634.281377  2.751955e+06  -66.320313
3238 2019-05-28  8664.559570           100         200300          0.011518  315.644307    634.575043  2.734919e+06  -54.290039
3239 2019-05-29  8276.250000           100         200400          0.012059  315.656366    634.867602  2.612451e+06 -388.309570
3240 2019-05-30  8550.669922           100         200500          0.011672  315.668038    635.160916  2.699173e+06  274.419922
3241 2019-05-31  8555.870117           100         200600          0.011665  315.679702    635.454224  2.700915e+06    5.200195
3242 2019-06-01  8737.910156           100         200700          0.011421  315.691124    635.747999  2.758481e+06  182.040039
3243 2019-06-02  8114.490234           100         200800          0.012299  315.703422    636.039985  2.561772e+06 -623.419922
3244 2019-06-03  7677.470215           100         200900          0.012999  315.716422    636.330537  2.423903e+06 -437.020019
3245 2019-06-04  7791.290039           100         201000          0.012809  315.729231    636.621448  2.459938e+06  113.819824
3246 2019-06-05  7807.359863           100         201100          0.012783  315.742014    636.912388  2.465112e+06   16.069824
3247 2019-06-06  8002.629883           100         201200          0.012471  315.754484    637.203935  2.526866e+06  195.270020
3248 2019-06-07  7933.779785           100         201300          0.012579  315.767064    637.495240  2.505226e+06  -68.850098
3249 2019-06-08  7643.439941           100         201400          0.013057  315.780121    637.785557  2.413646e+06 -290.339844
3250 2019-06-09  8021.000000           100         201500          0.012442  315.792563    638.077091  2.532972e+06  377.560059
3251 2019-06-10  7917.319824           100         201600          0.012605  315.805168    638.368274  2.500331e+06 -103.680176
3252 2019-06-11  8174.140137           100         201700          0.012209  315.817377    638.660234  2.581536e+06  256.820313
3253 2019-06-12  8218.299805           100         201800          0.012144  315.829521    638.952304  2.595582e+06   44.159668

[2018 rows x 9 columns]

In [11]:
print(df[df['price_diff'] > 0].count())

Date                1069
Close               1069
everytime_in        1069
accumulate_in       1069
everytime_buy_bt    1069
acc_buy_bt          1069
average_cost        1069
acc_value           1069
price_diff          1069
dtype: int64

In [12]:
2017-1069

948

In [ ]:
# logic = {'Open'  : 'first',
#          'High'  : 'max',
#          'Low'   : 'min',
#          'Close' : 'last',
#          'Volume': 'sum'}

# offset = pd.offsets.timedelta(days=-6)

# f = pd.read_clipboard(parse_dates=['Date'], index_col=['Date'])
# f.resample('W', loffset=offset).apply(logic)